### ISSUE TITLE
Adding a single hook

### ISSUE THREAD

**Issue by GabrielBB** [Raathigesh/hooks.guide#12]
Hi, i want to include this hook i made to your page: [react-use-session](https://github.com/GabrielBB/react-use-session). I see i have to create a new folder under _public_ but it looks like all those hooks there are part of some set of hooks, so the folder name is the set name. In my case i only have a single hook. So, what name should i give to the folder? My Github username or just the hook name?

**Comment by Raathigesh** [comment]
Hey, 

Please add it under the community folder. Thats where we intend to collect all the hooks contributed by the community.

**Comment by GabrielBB** [comment]
@Raathigesh Alright. Thanks. Closing issue
