### ISSUE TITLE
open-graph in head?

### ISSUE THREAD

**Issue by ysm0622** [Raathigesh/hooks.guide#9]
It would be nice to add open graph tags in [https://www.hooks.guide/](https://www.hooks.guide/) page!
👍 

Thank you for great project!

**Comment by Raathigesh** [comment]
If you could, feel free to add it and send a PR. The tags should go into `public/index.html`

**Comment by vivek12345** [comment]
This should add open graph tags.
https://github.com/Raathigesh/hooks.guide/pull/10
